server {
    listen 80;
    server_name _;

    client_max_body_size 2m;

    location = /__waf__/authorize {
        internal;
        proxy_pass http://app:8000/__waf__/authorize;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-WAF-Auth-Request 1;
        proxy_set_header X-Request-Id $request_id;
        proxy_set_header X-Original-Method $request_method;
        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header X-Edge-Content-Type $content_type;
        proxy_set_header X-Edge-User-Agent $http_user_agent;
        proxy_set_header X-Edge-Referer $http_referer;
        proxy_set_header X-Edge-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Edge-Real-IP $remote_addr;
    }

    location / {
        auth_request /__waf__/authorize;
        auth_request_set $waf_request_id $upstream_http_x_request_id;
        auth_request_set $waf_action $upstream_http_x_waf_action;
        proxy_set_header X-Request-Id $waf_request_id;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_pass http://app:8000;
    }

    error_page 403 = @waf_blocked;

    location @waf_blocked {
        default_type application/json;
        return 403 '{"error":"request_blocked","stage":"edge","request_id":"$waf_request_id","action":"$waf_action"}';
    }
}
